//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceParametersObservation) DeepCopyInto(out *InstanceParametersObservation) {
	*out = *in
	if in.TermintationTime != nil {
		in, out := &in.TermintationTime, &out.TermintationTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceParametersObservation.
func (in *InstanceParametersObservation) DeepCopy() *InstanceParametersObservation {
	if in == nil {
		return nil
	}
	out := new(InstanceParametersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceParametersParameters) DeepCopyInto(out *InstanceParametersParameters) {
	*out = *in
	if in.AlwaysPxe != nil {
		in, out := &in.AlwaysPxe, &out.AlwaysPxe
		*out = new(bool)
		**out = **in
	}
	if in.BillingCycle != nil {
		in, out := &in.BillingCycle, &out.BillingCycle
		*out = new(string)
		**out = **in
	}
	if in.Customdata != nil {
		in, out := &in.Customdata, &out.Customdata
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.IpxeScriptURL != nil {
		in, out := &in.IpxeScriptURL, &out.IpxeScriptURL
		*out = new(string)
		**out = **in
	}
	if in.Locked != nil {
		in, out := &in.Locked, &out.Locked
		*out = new(bool)
		**out = **in
	}
	if in.OperatingSystem != nil {
		in, out := &in.OperatingSystem, &out.OperatingSystem
		*out = new(string)
		**out = **in
	}
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(string)
		**out = **in
	}
	if in.ProjectSSHKeys != nil {
		in, out := &in.ProjectSSHKeys, &out.ProjectSSHKeys
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserSSHKeys != nil {
		in, out := &in.UserSSHKeys, &out.UserSSHKeys
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Userdata != nil {
		in, out := &in.Userdata, &out.Userdata
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceParametersParameters.
func (in *InstanceParametersParameters) DeepCopy() *InstanceParametersParameters {
	if in == nil {
		return nil
	}
	out := new(InstanceParametersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MarketRequest) DeepCopyInto(out *MarketRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MarketRequest.
func (in *MarketRequest) DeepCopy() *MarketRequest {
	if in == nil {
		return nil
	}
	out := new(MarketRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MarketRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MarketRequestList) DeepCopyInto(out *MarketRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MarketRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MarketRequestList.
func (in *MarketRequestList) DeepCopy() *MarketRequestList {
	if in == nil {
		return nil
	}
	out := new(MarketRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MarketRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MarketRequestObservation) DeepCopyInto(out *MarketRequestObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MarketRequestObservation.
func (in *MarketRequestObservation) DeepCopy() *MarketRequestObservation {
	if in == nil {
		return nil
	}
	out := new(MarketRequestObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MarketRequestParameters) DeepCopyInto(out *MarketRequestParameters) {
	*out = *in
	if in.DevicesMax != nil {
		in, out := &in.DevicesMax, &out.DevicesMax
		*out = new(int64)
		**out = **in
	}
	if in.DevicesMin != nil {
		in, out := &in.DevicesMin, &out.DevicesMin
		*out = new(int64)
		**out = **in
	}
	if in.Facilities != nil {
		in, out := &in.Facilities, &out.Facilities
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.InstanceParameters != nil {
		in, out := &in.InstanceParameters, &out.InstanceParameters
		*out = make([]InstanceParametersParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MaxBidPrice != nil {
		in, out := &in.MaxBidPrice, &out.MaxBidPrice
		*out = new(float64)
		**out = **in
	}
	if in.Metro != nil {
		in, out := &in.Metro, &out.Metro
		*out = new(string)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.WaitForDevices != nil {
		in, out := &in.WaitForDevices, &out.WaitForDevices
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MarketRequestParameters.
func (in *MarketRequestParameters) DeepCopy() *MarketRequestParameters {
	if in == nil {
		return nil
	}
	out := new(MarketRequestParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MarketRequestSpec) DeepCopyInto(out *MarketRequestSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MarketRequestSpec.
func (in *MarketRequestSpec) DeepCopy() *MarketRequestSpec {
	if in == nil {
		return nil
	}
	out := new(MarketRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MarketRequestStatus) DeepCopyInto(out *MarketRequestStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MarketRequestStatus.
func (in *MarketRequestStatus) DeepCopy() *MarketRequestStatus {
	if in == nil {
		return nil
	}
	out := new(MarketRequestStatus)
	in.DeepCopyInto(out)
	return out
}
